=== secu2/miage_pai_final/cabinetInfirmier/cabinetinfirmier.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema version="1.0"
           targetNamespace="http://localhost/schema/cabinetInfirmier"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://localhost/schema/cabinetInfirmier"
           elementFormDefault="qualified">

    <xs:element name="cabinet" type="Cabinet" />
    
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" />
            <xs:element name="adresse" type="Adresse" />
            <xs:element name="infirmiers" type="Infirmiers" />
            <xs:element name="patients" type="Patients" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" maxOccurs="unbounded" type="Infirmier" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <xs:element name="nom" />
            <xs:element name="prenom" />
            <xs:element name="photo" />
        </xs:sequence>
        <xs:attribute name="id" type="Id" />
    </xs:complexType>
    
    <xs:simpleType name="Id">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d\d\d" /> <!-- 3 digits -->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" maxOccurs="unbounded" type="Patient" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" />
            <xs:element name="prenom" />
            <xs:element name="sexe" type="Sexe" />
            <xs:element name="naissance" type="xs:date" />
            <xs:element name="numero" type="NumeroSecuriteSociale" />
            <xs:element name="adresse" type="Adresse" />
            <xs:element name="visite" type="Visite" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="NumeroSecuriteSociale">
        <xs:restriction base="xs:string">
            <xs:length value="15"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Adresse">
        <xs:all>
            <xs:element name="etage" minOccurs="0" type="xs:int" />
            <xs:element name="no" minOccurs="0" type="xs:int" />
            <xs:element name="rue" />
            <xs:element name="ville" />
            <xs:element name="codePostal" type="CodePostal" />
        </xs:all>
    </xs:complexType>
    
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{5}" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Visite">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="acte" type="Acte" />
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required" /> 
        <xs:attribute name="intervenant" type="Id" />
    </xs:complexType>
    
    <xs:complexType name="Acte">
        <xs:attribute name="id" type="Id" />
    </xs:complexType>
</xs:schema>

=== secu2/miage_pai_final/cabinetInfirmier/cabinetInfirmier.xml
<?xml version="1.0" encoding="UTF-8" ?>


<cabinet xmlns="http://localhost/schema/cabinetInfirmier"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://localhost/schema/cabinetInfirmier cabinetInfirmier.xsd">
    <nom>Soins à Grenoble</nom>
    <adresse>
        <no>60</no>
        <rue>Rue de la chimie</rue>
        <ville>Grenoble</ville>
        <codePostal>38041</codePostal>
    </adresse>
    <infirmiers>
        <infirmier id="001">
            <nom>Versaire</nom>
            <prenom>Annie</prenom>
            <photo>annie.jpg</photo>
        </infirmier>
        <infirmier id="002">
            <nom>Cent</nom>
            <prenom>Sally</prenom>
            <photo>sally.jpg</photo>
        </infirmier>
        <infirmier id="003">
            <nom>Nouie</nom>
            <prenom>Eva</prenom>
            <photo>eva.jpg</photo>
        </infirmier>
    </infirmiers>
    <patients>
        <patient>
            <nom>Aire</nom>
            <prenom>Axel</prenom>
            <sexe>M</sexe>
            <naissance>1993-06-13</naissance>
            <numero>193061305545319</numero>
            <adresse>
                <etage>4</etage>
                <no>46</no>
                <rue>Avenue Felix Viallet</rue>
                <ville>Grenoble</ville>
                <codePostal>38031</codePostal>
            </adresse>
            <visite date='2014-12-08' intervenant='001'>
                <acte id='103' />
                <acte id='104' />
                <acte id='109' />
                <acte id='105' />
            </visite>
        </patient>
        <patient>
            <nom>Orouge</nom>
            <prenom>Elvire</prenom>
            <sexe>F</sexe>
            <naissance>1980-03-08</naissance>
            <numero>280033851600581</numero>
            <adresse>
                <rue>rond-Point de la Croix de Vie</rue>
                <ville>La Tronche</ville>
                <codePostal>38700</codePostal>
            </adresse>
            <visite date='2014-12-08' intervenant="001">
                <acte id='103' />
            </visite>
        </patient>
        <patient>
            <nom>Pien</nom>
            <prenom>Oscare</prenom>
            <sexe>M</sexe>
            <naissance>1975-10-25</naissance>
            <numero>175103818500539</numero>
            <adresse>
                <rue>Rue Casimir Brenier</rue>
                <ville>Grenoble</ville>
                <codePostal>38000</codePostal>
            </adresse>
            <visite date='2014-12-08' intervenant="000">
            </visite>
        </patient>
        <patient>
            <nom>Kapoëtla</nom>
            <prenom>Xavier</prenom>
            <sexe>M</sexe>
            <naissance>2010-02-08</naissance>
            <numero>110023818500589</numero>
            <adresse>
                <no>25</no>
                <rue>Rue des Martyrs</rue>
                <ville>Grenoble</ville>
                <codePostal>38042</codePostal>
            </adresse>
            <visite date='2014-12-08'>
            </visite>
        </patient>
    </patients>
</cabinet>

=== secu2/miage_pai_final/cabinetInfirmier/Serveur2/data/cabinetInfirmier2-sorted.xml
<?xml version="1.0" encoding="UTF-8"?>
<cabinet xmlns="http://www.ujf-grenoble.fr/l3miage/cabinet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/cabinet cabinetInfirmier.xsd">
<nom>Soins Ã  Grenoble</nom>
<adresse>
<no>60</no>
<rue>Rue de la chimie</rue>
<ville>Grenoble</ville>
<codePostal>38041</codePostal>
</adresse>
<infirmiers>
<infirmier id="001">
<nom>Versaire</nom>
<prenom>Annie</prenom>
<photo>annie.jpg</photo>
</infirmier>
<infirmier id="002">
<nom>Cent</nom>
<prenom>Sally</prenom>
<photo>sally.jpg</photo>
</infirmier>
<infirmier id="003">
<nom>Nouie</nom>
<prenom>Eva</prenom>
<photo>eva.jpg</photo>
</infirmier>
</infirmiers>
<patients>




<patient xmlns="http://www.ujf-grenoble.fr/l3miage/cabinet">
<nom>Orouge</nom>
<prenom>Elvire</prenom>
<sexe>F</sexe>
<naissance>1980-03-08</naissance>
<numero>280033851600581</numero>
<adresse>
<rue>rond-Point de la Croix de Vie</rue>
<ville>La Tronche</ville>
<codePostal>38700</codePostal>
</adresse>
<visite date="2014-12-08" intervenant="001">
<acte id="103"/>
</visite>
</patient><patient xmlns="http://www.ujf-grenoble.fr/l3miage/cabinet">
<nom>Pien</nom>
<prenom>Oscare</prenom>
<sexe>M</sexe>
<naissance>1975-10-25</naissance>
<numero>175103818500539</numero>
<adresse>
<rue>Rue Casimir Brenier</rue>
<ville>Grenoble</ville>
<codePostal>38000</codePostal>
</adresse>
<visite date="2014-12-08" intervenant="000">
</visite>
</patient></patients>
</cabinet>
